CREATE TABLE USUARIO(CPF VARCHAR(20) PRIMARY KEY, nome VARCHAR(45), 
email VARCHAR(45), telefone1 VARCHAR(14), telefone2 VARCHAR(14));

CREATE TABLE CONTA_BANCARIA (agencia VARCHAR(5) PRIMARY KEY, 
CONTA VARCHAR(8) PRIMARY KEY, CPF VARCHAR(20));

CREATE TABLE CRIADOR (CPF VARCHAR(20), 
agencia VARCHAR(5) NOT NULL UNIQUE, 
conta VARCHAR(8) NOT NULL UNIQUE,
CONSTRAINT criador_fk FOREIGN KEY (CPF) REFERENCES USUARIO(CPF), 
CONSTRAINT agencia_fk FOREIGN KEY (agencia) REFERENCES CONTA_BANCARIA(agencia),
CONSTRAINT conta_fk FOREIGN KEY (conta) REFERENCES CONTA_BANCARIA(conta));

CREATE TABLE PREMIUM (CPF VARCHAR(20), data_cobranca DATE, 
CONSTRAINT premium_fk FOREIGN KEY (CPF) REFERENCES USUARIO(CPF));

CREATE TABLE EVENTO (CPF VARCHAR(20) PRIMARY KEY, numEvento NUMBER PRIMARY KEY, data DATE, 
CEP VARCHAR(9), numero NUMBER,
CONSTRAINT cpf_fk FOREIGN KEY (CPF) REFERENCES USUARIO(CPF));

CREATE TABLE ALBUM (id_album NUMBER PRIMARY KEY, CPF VARCHAR(8) NOT NULL UNIQUE,
titulo VARCHAR(45), capa VARCHAR(45), genero VARCHAR(45), 
total_faixas NUMBER, CONSTRAINT cpf_fk FOREIGN KEY (cpf) REFERENCES USUARIO(CPF));

CREATE TABLE MUSICA (id_musica number PRIMARY KEY, id_album NUMBER NOT NULL, 
titulo VARCHAR(45), duracao NUMBER, capa VARCHAR(45))